module Orchestration
  class StepActionEditorComponent < ViewComponent::Base
    def initialize: (step_action: StepAction, step_action_counter: Integer, step_action_iteration: untyped, pipeline: Pipeline, step: Step, upstream_schemas: Hash[String, untyped?], validator_results: Array[Pipeline::Validator::StepResult]) -> void
    def validation_errors: () -> Array[Pipeline::Validator::Issue]
  end
end
