module Orchestration
  class StepsListComponent < ViewComponent::Base
    def initialize: (pipeline: Pipeline, steps: untyped, actions: untyped, index: Orchestration::UpstreamSchemaIndex) -> void
  end
end
