module Orchestration
  class StepsListComponent < ViewComponent::Base
    @pipeline: Pipeline
    @steps: Array[Step]
    @actions: Array[Action]
    @upstream_schemas_per_step: Hash[Integer, Hash[String, json_object?]]
    @validator_results_per_step: Hash[Integer, Array[Pipeline::Validator::StepResult]]

    def initialize: (pipeline: Pipeline, steps: Array[Step], actions: Array[Action]) -> void

    private

    def compute_upstream_schemas_per_step: () -> Hash[Integer, Hash[String, json_object?]]
    def compute_validator_results_per_step: () -> Hash[Integer, Array[Pipeline::Validator::StepResult]]
  end
end
