module Emails
  module Adapters
    class GmailMessageParser
      @message: Google::Apis::GmailV1::Message

      def initialize: (Google::Apis::GmailV1::Message message) -> void
      def to_h: () -> message

      private

      def header_value: (Array[Google::Apis::GmailV1::MessagePartHeader] headers, String name) -> String?
    end
  end
end
