module Emails
  module Adapters
    class GmailAdapter < BaseAdapter
      APPLICATION_NAME: String
      SCOPE: Array[String]

      @credentials_path: String
      @labels: Array[label]
      @token_path: String
      @service: Google::Apis::GmailV1::GmailService

      def self.from_env: (?credentials_path: String?, ?token_path: String?) -> GmailAdapter

      def initialize: (credentials_path: String, token_path: String) -> void
      def authorize: () -> untyped
      def modify_labels: (String message_id, ?add: Array[String], ?remove: Array[String], ?source_mailbox: String?) -> untyped
      def get_message: (String | Integer message_id, **untyped) -> untyped
      def create_label: (name: String) -> untyped

      private

      def fetch_messages: (Integer max_results, Integer offset) { (Integer page_size, String? page_token) -> Google::Apis::GmailV1::ListMessagesResponse? } -> Array[message]
      def find_existing_label: (String name) -> untyped

      def build_label_ids: (Array[String] | String) -> Array[String]

      def list_message: (String message_id) -> message?
    end
  end
end
