module Emails
  module Adapters
    class YahooMessageParser
      @uid: Integer
      @mail: Mail::Message
      @mailbox: String

      def initialize: (Integer uid, Mail::Message mail, String mailbox) -> void
      def to_h: () -> message

      private

      def decode_subject: () -> String
      def format_addresses: (String | Array[String] | nil addresses) -> String
    end
  end
end
