module Emails
  module Adapters
    class YahooMessageParser
      @uid: Integer
      @mail: Mail::Message
      @mailbox: String

      def initialize: (Integer uid, Mail::Message mail, String mailbox) -> void
      def to_h: () -> message
    end
  end
end
