module Emails
  module Adapters
    type imap_config = {
      host: String,
      port: Integer,
      username: String,
      password: String
    }
    class YahooAdapter < BaseAdapter
      @imap_config: imap_config
      @labels: Array[label]
      @mutex: Mutex
      @current_mailbox: String?
      @imap: Net::IMAP?

      def self.from_env: (?username: String?, ?password: String?, ?host: String, ?port: Integer) -> YahooAdapter

      def initialize: (host: String, port: Integer, username: String, password: String) -> void
      def get_message: (String | Integer message_id, ?label: String?) -> untyped
      def modify_labels: (String | Integer message_uid, ?add: Array[String], ?remove: Array[String], ?source_mailbox: String) -> modify_result

      private

      def imap: () -> Net::IMAP
      def ensure_mailbox: (String mailbox) -> void
      def imap_flag?: (String label) -> bool

      HEADER_FIELDS: Array[String]
      FULL_FIELDS: Array[String]

      def with_lock: [T] () { () -> T } -> T
      def build_mailbox: (String?) -> String
      def parse_mail: (Integer uid, Array[String] fields) -> Mail::Message?
      def list_message: (Integer uid, String mailbox) -> message?
    end
  end
end
