module UI
  class DetailCardComponent < ViewComponent::Base
    class Attribute
      attr_reader label: String
      attr_reader attribute: Symbol
      attr_reader type: Symbol
      attr_reader variant_map: Hash[String, Symbol]

      def self.from: (Hash[Symbol, primitive] hash) -> Attribute
    end

    @entity: ApplicationRecord
    @attributes: Array[Hash[Symbol, primitive]]

    def initialize: (entity: ApplicationRecord, attributes: Array[Hash[Symbol, primitive]]) -> void
    def value_for: (Attribute attr) -> primitive
    def variant_for: (Attribute attr, primitive value) -> Symbol
    def text_classes_for: (Attribute attr) -> String
    def json_display: (json_object_value val) -> String

    def with_status_badge: (label: String, ?variant: Symbol) -> StatusBadgeComponent
    def status_badge: () -> String?
    def status_badge?: () -> bool
  end
end
