module UI
  class JsonDisclosureComponent < ViewComponent::Base
    @label: String
    @data: json_object_value

    def initialize: (label: String, data: json_object_value) -> void
    def render?: () -> bool
    def pretty_json: () -> String
  end
end
