module UI
  class StatusBadgeComponent < ViewComponent::Base
    VARIANT_CLASSES: Hash[Symbol, String]

    def initialize: (label: String, ?variant: Symbol) -> void
    def classes: () -> String
  end
end
