inherit_gem:
  rubocop-rails-omakase: rubocop.yml
plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-on-rbs

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 10