module Orchestration
  class PipelineRunner
    include SteepHacks

    @pipeline_run: PipelineRun
    @prompt_resolver: _PromptResolver

    def initialize: (PipelineRun pipeline_run, ?prompt_resolver: _PromptResolverFactory | _PromptResolver) -> void
    def run: () -> void

    private

    def build_initial_outputs: () -> Hash[String, json_object]
    def process_steps: (Hash[String, json_object] previous_outputs) -> void
    def handle_step_failure: (Array[ActionRun] action_runs) -> bool
    def accumulate_step_outputs: (Array[ActionRun] action_runs, Hash[String, json_object] previous_outputs) -> void
    def run_step: (Step step, Hash[String, json_object] previous_outputs) -> Array[ActionRun]
    def prepare_action_runs: (Step step, Hash[String, json_object] previous_outputs) -> Array[ActionRun]
    def create_action_run: (StepAction step_action) -> ActionRun
    def resolve_action_input: (ActionRun action_run, StepAction step_action, Hash[String, json_object] previous_outputs) -> void
    def run_actions_in_parallel: (Array[ActionRun] action_runs) -> void
    def execute_action: (ActionRun action_run) -> void
  end
end
