module Pipeline
  class Logger
    LEVELS: Array[String]

    class MultiIO
      @targets: Array[IO]

      def initialize: (*IO targets) -> void
      def write: (::_ToS message) -> void
      def flush: () -> void
      def close: () -> void
    end

    @logger: ::Logger

    def initialize: (?level: Symbol | String, ?output: IO, ?log_file: String?) -> void
    def debug: (?::_ToS) ?{ () -> ::_ToS } -> void
    def debug?: () -> bool
    def info: (?::_ToS) ?{ () -> ::_ToS } -> void
    def info?: () -> bool
    def warn: (?::_ToS) ?{ () -> ::_ToS } -> void
    def warn?: () -> bool
    def error: (?::_ToS) ?{ () -> ::_ToS } -> void
    def error?: () -> bool
  end
end
