module Pipeline
  class TestWorkflow
    @model: String
    @logger: Logger
    @date: Date

    def initialize: (model: String, logger: Logger, ?date: String | Date) -> void
    def run: () -> json_object
    def step1: (provider: String, after: String | Date, before: String | Date) -> Array[json_object]
    def step2: (emails: Array[json_object]) -> json_object_value
    def step3: (emails: Array[json_object], tags: Array[json_object]) -> json_object_value
    def step4: (emails: Array[json_object]) -> json_object_value
    def step5: (emails: Array[json_object]) -> json_object_value
    def step6: (?emails: Array[json_object]) -> json_object_value
    def step7: (?emails: Array[json_object]) -> json_object_value
    def fetach_emails: () -> Array[json_object]
    def start_date: () -> Date
    def end_date: () -> Date
  end
end
