module Emails
  class SearchTool < RubyLLM::Tool
    def self.readonly?: () -> bool
    def name: () -> String
    def execute: (provider: String, query: String, ?max_results: Integer, ?label: String?) -> Array[Emails::message]
  end
end
