module Settings
  class EmailConnectorsController < ApplicationController
    @email_connectors: EmailConnector::relation
    @email_connector: EmailConnector

    def index: () -> void
    def show: () -> void
    def new: () -> void
    def edit: () -> void
    def create: () -> void
    def update: () -> void
    def destroy: () -> void
    def test: () -> void
    def setup: () -> void
    def oauth_callback: () -> void

    private

    def exchange_gmail_oauth_code: (EmailConnector connector) -> Signet::OAuth2::Client
    def set_email_connector: () -> void
    def email_connector_params: () -> ActionController::Parameters
  end
end
