class Chat < ApplicationRecord
  type relation = _Relation[Chat, Integer]

  def model_id: () -> Integer?
  def model_id=: (Integer?) -> Integer?
  def model: () -> Model?
  def model=: (Model?) -> Model?

  def messages: () -> Message::relation
  def action_runs: () -> Orchestration::ActionRun::relation
  def index_attributes: () -> Hash[Symbol, primitive]
  def show_attributes: () -> Hash[Symbol, primitive]
  def to_llm_context: () -> Hash[Symbol, String]
  def ground_truth: () -> json_object?
end
