class EmailVector < ApplicationRecord
  type email_vector_result = { email_id: String, distance: Float }
  def self.upsert_embedding: (email_id: String, embedding: Array[Float]) -> void
  def self.search: (Array[Float] embedding, ?limit: Integer) -> Array[email_vector_result]

  def self.serialize: (Array[Float] embedding) -> String
end
