class Message < ApplicationRecord
  type relation = _Relation[Message, Integer]

  def role: () -> String?
  def role=: (String?) -> String?
  def content: () -> String?
  def content=: (String?) -> String?
  def chat_id: () -> Integer?
  def chat_id=: (Integer?) -> Integer?
  def model_id: () -> Integer?
  def model_id=: (Integer?) -> Integer?

  def parent_tool_call: () -> ToolCall?
  def parent_tool_call=: (ToolCall?) -> ToolCall?
end
