class ApplicationMailsController < ApplicationController
  @query: String?
  @pagy: Pagy
  @mails: ApplicationMail::relation
  @mail: ApplicationMail

  def index: () -> void
  def show: () -> void
  def new: () -> void
  def create: () -> void
  def edit: () -> void
  def update: () -> void
  def destroy: () -> void
  def batch: () -> void

  private

  def set_mail: () -> void
  def mail_params: () -> ActionController::Parameters
end
