class ModelsController < ApplicationController
  @models: ActiveRecord::Relation
  @pagy: Pagy
  @query: String?

  def index: () -> void
  def sync: () -> void

  private

  def model_matches?: (RubyLLM::Models::model model, String query) -> bool
end
