module Orchestration
  class ActionsController < ApplicationController
    @action: Orchestration::Action
    @actions: Orchestration::Action::relation
    @agents: Orchestration::Agent::relation

    def index: () -> void
    def new: () -> void
    def create: () -> void
    def edit: () -> void
    def update: () -> void
    def destroy: () -> void

    private

    def set_action: () -> void
    def load_agents: () -> void
    def action_params: () -> ActionController::Parameters
  end
end
