module Orchestration
  class SchemaBuildersController < ApplicationController
    @builder: Orchestration::SchemaBuilder
    @json: String
    @error: String?

    def build: () -> void
    def add_property: () -> void
    def remove_property: () -> void
    def change_type: () -> void
    def parse: () -> void

    private

    def render_parse_error: (String message) -> void
    def parse_json: () -> json_object
    def parse_path: () -> Array[String]
    def builder_params: () -> ActionController::Parameters
  end
end
