module Orchestration
  class StepsController < ApplicationController
    def create: () -> void
    def update: () -> void
    def destroy: () -> void
    def move_up: () -> void
    def move_down: () -> void
    def toggle: () -> void

    private

    def set_pipeline: () -> void
    def set_step: () -> void
    def render_pipeline_show: () -> void
    def step_params: () -> ActionController::Parameters
  end
end
