module Orchestration
  class StepActionsController < ApplicationController
    @pipeline: Orchestration::Pipeline
    @step: Orchestration::Step
    @step_action: Orchestration::StepAction

    def create: () -> void
    def update: () -> void
    def destroy: () -> void

    private

    def build_input_mapping_form: () -> Orchestration::InputMappingForm
    def build_notice_message: (Orchestration::InputMappingUpdater::Result? result) -> String
    def build_error_summary: (Orchestration::InputMappingForm form) -> String
    def set_pipeline: () -> void
    def set_step: () -> void
    def step_action_params: () -> ActionController::Parameters?
    def parse_input_mapping: () -> ([json_object, nil] | [json_object, String])
  end
end
