module Orchestration
  class InputMappingUpdater
    class Result
      attr_reader saved: bool
      attr_reader errors: Array[Pipeline::Validator::Issue]
      attr_reader warnings: Array[Pipeline::Validator::Issue]

      def self.new: (saved: bool, errors: Array[Pipeline::Validator::Issue], warnings: Array[Pipeline::Validator::Issue]) -> instance
    end

    def self.call: (step_action: StepAction, input_mapping: json_object) -> Result

    @step_action: StepAction
    @pipeline: Orchestration::Pipeline
    @input_mapping: json_object

    def initialize: (step_action: StepAction, input_mapping: json_object) -> void
    def call: () -> Result
  end
end
