module Orchestration
  class OutputKeyDeriver
    def self.call: (action_name: String, step: Step) -> String

    def initialize: (action_name: String, step: Step) -> void
    def call: () -> String

    private

    attr_reader action_name: String
    attr_reader step: Step
  end
end
