module Orchestration
  class QueryExecutor
    include Executable
    extend Executable::ClassMethods
    extend Records::ModelResolver

    def self.call: (table: String, column_name: String, column_values: Array[json_object_value], ?columns: Array[String]?) -> Hash[String, Array[json_object]]

    def self.dig_path: (json_object hash, String path) -> json_object_value
  end
end
