module Orchestration
  class SchemaValidator
    Error: singleton(StandardError)

    @schema: json_object?

    def initialize: (json_object? schema) -> void
    def validate!: (json_object_value data) -> void

    private

    def validate_node!: (json_object_value value, json_object? schema, String path) -> void
  end
end
