module Orchestration
  class ActionRun < ApplicationRecord
    type relation = _Relation[ActionRun, Integer]

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[ActionRun]
      include ::ActiveRecord::Relation::Methods[ActionRun, ::Integer]
    end

    STATUSES: Array[String]

    def self.table_name: () -> String

    def status: () -> String?
    def status=: (String?) -> String?
    def input: () -> json_object?
    def input=: (json_object?) -> json_object?
    def output: () -> json_object?
    def output=: (json_object?) -> json_object?
    def agent_snapshot: () -> json_object?
    def agent_snapshot=: (json_object?) -> json_object?
    def error_details: () -> json_object?
    def error_details=: (json_object?) -> json_object?
    def error: () -> String?
    def error=: (String?) -> String?
    def started_at: () -> Time?
    def started_at=: (Time?) -> Time?
    def finished_at: () -> Time?
    def finished_at=: (Time?) -> Time?

    def pipeline_run: () -> PipelineRun
    def pipeline_run=: (PipelineRun) -> PipelineRun
    def step_action: () -> StepAction
    def step_action=: (StepAction) -> StepAction
    def chat: () -> Chat?
    def chat=: (Chat?) -> Chat?
    def chat_id: () -> Integer?
    def chat_id=: (Integer?) -> Integer?

    def ground_truth: () -> json_object?
    def index_attributes: () -> { status: String?, action: String, started_at: Time?, finished_at: Time? }
    def show_attributes: () -> { status: String?, action: String, input: json_object?, output: json_object?, error: String?, error_details: json_object?, agent_snapshot: json_object?, started_at: Time?, finished_at: Time? }
    def to_llm_context: () -> { action: String, input: json_object?, status: String?, agent_snapshot: json_object? }
  end
end
