module Orchestration
  class Action < ApplicationRecord
    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def agent_class: () -> String?
    def agent_class=: (String?) -> String?
    def description: () -> String?
    def description=: (String?) -> String?
    def model: () -> String?
    def model=: (String?) -> String?
    def tools: () -> Array[String]?
    def tools=: (Array[String]?) -> Array[String]?
    def prompt: () -> String?
    def prompt=: (String?) -> String?
    def params: () -> Hash[String, untyped]?
    def params=: (Hash[String, untyped]?) -> Hash[String, untyped]?

    def step_actions: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::StepAction]

    private

    def agent_class_must_be_valid: () -> void
  end
end
