module Orchestration
  class Action < ApplicationRecord
    type relation = _Relation[Action, Integer]

    def self.table_name: () -> String
    def self.with_pipeline_counts: () -> relation

    def name: () -> String?
    def name=: (String?) -> String?
    def kind: () -> String
    def kind=: (String) -> String
    def agent?: () -> bool
    def service?: () -> bool
    def agent_id: () -> Integer?
    def agent_id=: (Integer?) -> Integer?
    def agent_class: () -> String?
    def agent_class=: (String?) -> String?
    def description: () -> String?
    def description=: (String?) -> String?
    def input_schema: () -> json_object?

    def step_actions: () -> StepAction::relation
    def agent: () -> Agent?

    private

    def kind_specific_fields_valid: () -> void
    def validate_service_class: () -> void
  end
end
