module Orchestration
  class Agent < ApplicationRecord
    type relation = _Relation[Agent, Integer]

    ALLOWED_TOOL_NAMESPACES: Array[String]

    def self.available_tools: () -> Array[String]
    def self.tool_class_name_from_path: (String path) -> String?
    def self.available_models: () -> Array[[String, Array[String]]]
    def self.with_action_counts: () -> relation

    def actions: () -> Action::relation

    def name: () -> String
    def name=: (String) -> String
    def description: () -> String?
    def description=: (String?) -> String?
    def model: () -> String?
    def model=: (String?) -> String?
    def tools: () -> Array[String]
    def tools=: (Array[String]) -> Array[String]
    def prompt: () -> String?
    def prompt=: (String?) -> String?
    def input_schema: () -> json_object?
    def input_schema=: (json_object?) -> json_object?
    def output_schema: () -> json_object?
    def output_schema=: (json_object?) -> json_object?
    def enabled: () -> bool
    def enabled=: (bool) -> bool
    def enabled?: () -> bool

    private

    def tools_must_be_valid: () -> void
    def validate_tool: (String tool) -> void
    def ensure_not_referenced: () -> void
  end
end
