module Orchestration
  class Agent < ApplicationRecord
    ALLOWED_TOOL_NAMESPACES: Array[String]

    def self.available_tools: () -> Array[String]
    def self.available_models: () -> Array[[String, Array[String]]]

    def actions: () -> ActiveRecord::Associations::CollectionProxy

    def name: () -> String
    def name=: (String) -> String
    def description: () -> String?
    def description=: (String?) -> String?
    def model: () -> String?
    def model=: (String?) -> String?
    def tools: () -> Array[String]
    def tools=: (Array[String]) -> Array[String]
    def prompt: () -> String?
    def prompt=: (String?) -> String?
    def params: () -> Hash[String, untyped]
    def params=: (Hash[String, untyped]) -> Hash[String, untyped]
    def output_schema: () -> Hash[String, untyped]?
    def output_schema=: (Hash[String, untyped]?) -> Hash[String, untyped]?
    def enabled: () -> bool
    def enabled=: (bool) -> bool
    def enabled?: () -> bool

    private

    def tools_must_be_valid: () -> void
    def ensure_not_referenced: () -> void
  end
end
