module Orchestration
  class Pipeline < ApplicationRecord
    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def description: () -> String?
    def description=: (String?) -> String?
    def model: () -> String?
    def model=: (String?) -> String?
    def cron_expression: () -> String?
    def cron_expression=: (String?) -> String?
    def enabled: () -> bool
    def enabled=: (bool) -> bool
    def initial_input_schema: () -> Hash[String, untyped]?
    def initial_input_schema=: (Hash[String, untyped]?) -> Hash[String, untyped]?

    def next_run_at: (?from: Time) -> Time?

    def steps: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::Step]
    def pipeline_runs: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::PipelineRun]

    private

    def cron_expression_parseable: () -> void
  end
end
