module Orchestration
  class Pipeline < ApplicationRecord
    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def description: () -> String?
    def description=: (String?) -> String?
    def cron_expression: () -> String?
    def cron_expression=: (String?) -> String?
    def enabled: () -> bool
    def enabled=: (bool) -> bool

    def next_run_at: (?from: Time) -> Time?

    def steps: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::Step]
    def pipeline_runs: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::PipelineRun]
  end
end
