module Orchestration
  class PipelineRun < ApplicationRecord
    type relation = _Relation[PipelineRun, Integer]

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[PipelineRun]
      include ::ActiveRecord::Relation::Methods[PipelineRun, ::Integer]
    end

    STATUSES: Array[String]
    TRIGGERED_BY: Array[String]

    def self.table_name: () -> String

    def status: () -> String?
    def status=: (String?) -> String?
    def triggered_by: () -> String?
    def triggered_by=: (String?) -> String?
    def started_at: () -> Time?
    def started_at=: (Time?) -> Time?
    def finished_at: () -> Time?
    def finished_at=: (Time?) -> Time?
    def error: () -> String?
    def error=: (String?) -> String?
    def initial_input: () -> json_object?
    def initial_input=: (json_object?) -> json_object?

    def pipeline: () -> Pipeline
    def pipeline=: (Pipeline) -> Pipeline
    def action_runs: () -> ActionRun::ActiveRecord_Associations_CollectionProxy
  end
end
