module Orchestration
  class Step < ApplicationRecord
    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def position: () -> Integer?
    def position=: (Integer?) -> Integer?
    def input_mapping: () -> Hash[String, untyped]?
    def input_mapping=: (Hash[String, untyped]?) -> Hash[String, untyped]?
    def enabled: () -> bool
    def enabled=: (bool) -> bool
    def enabled?: () -> bool

    def swap_position_with: (Step other) -> void

    def self.derive_status: (Array[ActionRun] action_runs) -> String

    def pipeline: () -> Pipeline
    def pipeline=: (Pipeline) -> Pipeline
    def step_actions: () -> ActiveRecord::Associations::CollectionProxy
    def actions: () -> ActiveRecord::Associations::CollectionProxy
  end
end
