module Orchestration
  class StepAction < ApplicationRecord
    def self.table_name: () -> String

    def output_key: () -> String
    def output_key=: (String) -> String
    def input_mapping: () -> Hash[String, untyped]?
    def input_mapping=: (Hash[String, untyped]?) -> Hash[String, untyped]?
    def position: () -> Integer?
    def position=: (Integer?) -> Integer?
    def step: () -> Orchestration::Step
    def step=: (Orchestration::Step) -> Orchestration::Step
    def action: () -> Orchestration::Action
    def action=: (Orchestration::Action) -> Orchestration::Action
  end
end
