module Orchestration
  class Step < ApplicationRecord
    type relation = _Relation[Step, Integer]

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[Step]
      include ::ActiveRecord::Relation::Methods[Step, ::Integer]
    end

    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def position: () -> Integer?
    def position=: (Integer?) -> Integer?
    def input_mapping: () -> json_object?
    def input_mapping=: (json_object?) -> json_object?
    def enabled: () -> bool
    def enabled=: (bool) -> bool
    def enabled?: () -> bool

    def swap_position_with: (Step other) -> void

    def self.derive_status: (Array[ActionRun] action_runs) -> String

    def pipeline: () -> Pipeline
    def pipeline=: (Pipeline) -> Pipeline
    def step_actions: () -> StepAction::ActiveRecord_Associations_CollectionProxy
    def actions: () -> Action::relation
  end
end
