module Orchestration
  class Step < ApplicationRecord
    def self.table_name: () -> String

    def name: () -> String?
    def name=: (String?) -> String?
    def position: () -> Integer?
    def position=: (Integer?) -> Integer?
    def input_mapping: () -> Hash[String, untyped]?
    def input_mapping=: (Hash[String, untyped]?) -> Hash[String, untyped]?

    def swap_position_with: (Orchestration::Step other) -> void

    def self.derive_status: (Array[Orchestration::ActionRun] action_runs) -> String

    def pipeline: () -> Orchestration::Pipeline
    def pipeline=: (Orchestration::Pipeline) -> Orchestration::Pipeline
    def step_actions: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::StepAction]
    def actions: () -> ActiveRecord::Associations::CollectionProxy[Orchestration::Action]
  end
end
