module Records
  class ReadSchemaTool < RubyLLM::Tool
    def name: () -> String
    def execute: (table: String) -> { headers: Array[String] }

    private
    def resolve_model: (String table) -> untyped
  end
end
