module RuboCop
  module Cop
    module App
      class NoTestDoubles < ::RuboCop::Cop::Base
        MSG: String
        FORBIDDEN: Array[Symbol]

        def on_send: (::RuboCop::Cop::_Node node) -> void

        private

        def spec_file?: () -> bool
      end
    end
  end
end
