module Rails
  def self.application=: (Application) -> void
                       | ...
  def self.cache: () -> ActiveSupport::Cache::Store
                | ...
  def self.cache=: (ActiveSupport::Cache::Store) -> void
                 | ...
  def self.logger: () -> ActiveSupport::Logger
                 | ...
  def self.logger=: (ActiveSupport::Logger) -> void
                  | ...
  def self.env: () -> ActiveSupport::StringInquirer
              | ...
  def self.root: () -> Pathname
               | ...
end

module ActiveSupport
  class StringInquirer < String
    def test?: () -> bool
    def development?: () -> bool
    def production?: () -> bool
  end
end

module ActiveRecord
  # module QueryMethods
  #   class WhereChain[Relation]
  #     def not: (**top) -> Relation
  #     def group: (*(Symbol | String | Arel::Attributes::Attribute)) -> Relation
  #   end
  # end

  class Relation
    def offset: (Integer) -> self
    def limit: (Integer | Arel::Nodes::SqlLiteral | nil) -> self
  end

  module Validations
    class UniquenessValidator
      type validator_options = { conditions: _Callable | nil, scope: Symbol | Array[Symbol] | nil, class: Class? }
      def attributes: () -> Array[Symbol | String]
      def options: () -> validator_options
    end
  end

  # rubocop:disable RBS/Lint/NoUntyped
  class Result
    def map: [T] () { (Hash[String, untyped]) -> T } -> Array[T]
  end
  # rubocop:enable RBS/Lint/NoUntyped
end

class TCPServer
  def self.new: (String host, Integer port) -> instance
              | (Integer port) -> instance
end

class CGI
  def self.unescape: (String string, ?Encoding encoding) -> String
end

module Net
  class IMAP
    class MailboxData
      def name: () -> String
      def attr: () -> Array[Symbol]
    end

    class FetchData
      def attr: () -> Hash[String, String]
    end

    class NoResponseError < StandardError
    end

    class ByeResponseError < StandardError
    end

    def initialize: (String host, ?port: Integer, ?ssl: bool | Hash[Symbol, primitive]) -> void
    def login: (String user, String password) -> void
    def logout: () -> void
    def disconnect: () -> void
    def select: (String mailbox) -> void
    def uid_search: (Array[String] criteria) -> Array[Integer]
    def uid_fetch: (Integer uid, Array[String] | String fields) -> Array[FetchData]?
    def uid_copy: (Integer uid, String mailbox) -> void
    def uid_store: (Integer uid, String attr, Array[String | Symbol] flags) -> void
    def expunge: () -> void
    def list: (String refname, String mailbox) -> Array[MailboxData]?
    def status: (String mailbox, Array[String] attrs) -> Hash[String, Integer?]
    def create: (String mailbox_name) -> void
  end
end

module Google
  module Apis
    class ClientError < StandardError
    end

    module GmailV1
      class GmailService
        def client_options: () -> ClientOptions
        def authorization=: (Signet::OAuth2::Client auth) -> void
        def list_user_messages: (String user_id, ?max_results: Integer, ?q: String?, ?page_token: String?, ?label_ids: Array[String]?) -> ListMessagesResponse?
        def get_user_message: (String user_id, String message_id, ?format: String, ?metadata_headers: Array[String]?) -> Message?
        def list_user_labels: (String user_id) -> ListLabelsResponse?
        def get_user_label: (String user_id, String label_id) -> LabelWithCount?
        def modify_message: (String user_id, String message_id, ModifyMessageRequest request) -> Message?
        def create_user_label: (String user_id, Label label) -> Label?
        def get_user_profile: (String user_id) -> void
      end

      class ClientOptions
        def application_name=: (String) -> String
      end

      class ListLabelsResponse
        def labels: () -> Array[Label]?
      end

      class LabelWithCount < Label
        def messages_total: () -> Integer?
      end

      class Label
        def initialize: (?name: String?) -> void
        def name: () -> String?
        def id: () -> String?
        def type: () -> String?
      end

      class Message
        def id: () -> String?
        def payload: () -> MessagePart
        def label_ids: () -> Array[String]?
        def snippet: () -> String?
        def thread_id: () -> String?
      end

      class MessagePart
        def headers: () -> Array[MessagePartHeader]
        def body: () -> MessagePartBody?
        def parts: () -> Array[MessagePart]?
        def mime_type: () -> String?
      end

      class MessagePartBody
        def data: () -> String?
        def attachment_id: () -> String?
      end

      class MessagePartHeader
        def name: () -> String?
        def value: () -> String?
      end

      class ListMessagesResponse
        def messages: () -> Array[Message]?
        def next_page_token: () -> String?
        def result_size_estimate: () -> Integer?
      end

      class ModifyMessageRequest
        def initialize: (?add_label_ids: Array[String]?, ?remove_label_ids: Array[String]?) -> void
      end
    end
  end

  module Auth
    class ClientId
      def self.from_file: (String) -> instance
    end

    class UserAuthorizer
      def initialize: (ClientId client_id, Array[String] scope, Stores::FileTokenStore token_store, ?legacy_callback_uri: String, ?callback_uri: String, ?code_verifier: String) -> void
      def get_credentials: (String user_id, ?Array[String] scope) -> Signet::OAuth2::Client?
      def get_and_store_credentials_from_code: (user_id: String, code: String, base_url: String) -> Signet::OAuth2::Client
      def get_authorization_url: (?base_url: String) -> String
    end

    module Stores
      class FileTokenStore
        def initialize: (file: String) -> void
      end
    end
  end
end

module JSON
  def self?.parse: (string source, ?symbolize_names: bool) -> json_object_value
                 | ...
end

module ViewComponent
  class Base
    def render_in: (view_context: ActionView::Base) -> String
    def render: () -> String
  end
end

class Pagy
end

class Array[unchecked out Elem]
  def index_by: [K] () { (Elem) -> K } -> Hash[K, Elem]
end

module Arel
  module Nodes
    class Join
    end
  end
end

# rubocop:disable RBS/Lint/NoUntyped
module Arel
  class Table
    def join: (untyped relation, ?untyped klass) -> SelectManager
            | ...
  end

  class SelectManager
    def on: (*untyped exprs) -> self
          | ...
    def join_sources: () -> Array[Arel::Nodes::Join]
  end
end
# rubocop:enable RBS/Lint/NoUntyped

