module Emails
  type fetch_result = {
    'emails' => Array[message],
  }
  class FetchExecutor
    DEFAULT_DATE: String
    DEFAULT_PROVIDERS: Array[String]
    DEFAULT_MAX_RESULTS: Integer

    include Orchestration::Executable
    extend Orchestration::Executable::ClassMethods
    def self.call: (?date: String?, ?providers: Array[String], ?max_results: Integer) -> fetch_result
  end
end
