class PipelineRunJob < ApplicationJob
  def perform: (Integer pipeline_run_id) -> void

  private

  def run_actions_in_parallel: (Array[Orchestration::ActionRun] action_runs) -> void
  def execute_action: (Orchestration::ActionRun action_run) -> void
  def build_agent: (Orchestration::Action action, Hash[String, untyped] params) -> untyped
end
