module Interviews
  class CsvExportService
    @ids: Array[String] | Array[Integer] | nil
    @columns: Array[String]

    def initialize: (ids: Array[String] | Array[Integer] | nil) -> void
    def call: () -> String
  end
end
