module Async
  module Helpers
    def self.with_semaphore: [T, U] (?concurrency: Integer, ?items: Array[T]) { (T) -> (Array[U] | U) } -> Array[U]
    def self.with_barrier: [T] (?concurrency: Integer, ?items: Array[T]) { (T) -> void } -> void
  end
end
